import Overview from "@/components/Overview";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
      <main className="flex items-start md:items-center justify-center bg-[#152938] w-screen h-screen py-10 p-5 md:py-5">
        <Overview />
      </main>
  );
}
